name: Build DMG for Disk Utility

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-dmg:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Build the app
        run: |
          cd DiskUtility
          xcodebuild -scheme DiskUtility -configuration Release -derivedDataPath build

      - name: Create DMG file
        run: |
          APP_PATH="DiskUtility/build/Build/Products/Release/DiskUtility.app"
          create-dmg "$APP_PATH" --overwrite --dmg-title "Disk Utility" --out "." --dmgpath "DiskUtility.dmg"

      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: disk-utility-dmg
          path: ./DiskUtility.dmg
